### ISSUE TITLE
Armv8 aarch64 compile fails

### ISSUE THREAD

**Issue by babyrig** [meritlabs/merit-miner#9]
Can you guide me how to achieve compile in the armv8 or if are possible at this moment ? 

and if possible can you check this other miner is armv8 compatible maybe need some tweak because I can compile and running but are m7m algo:
https://github.com/glukolog/m-cpuminer-v2.1-armv8
thanks

with the actual code trying to compile:

all deps installed fine

followed the instructions to build in a linux machine Ubuntu 16.4.4 LTS

Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                8
gcc version 8.1.0 (GCC)

Errors:
g++ -DHAVE_CONFIG_H -I. -I..    -Wall -O3 -g -O2 -march=native -MT cuckoo.o -MD -MP -MF $depbase.Tpo -c -o cuckoo.o cuckoo.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from cuckoo.cpp:16:
siphash.h:17:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h> // for _mm256_* intrinsics
          ^~~~~~~~~~~~~
compilation terminated.
